### ISSUE TITLE
Final line of inclusion / exclusion group seems to be getting left out

### ISSUE THREAD

**Issue by chrisyxlee** [chrisyxlee/files-changed-action#1]
i.e.

```yaml
      - id: changed-files
        uses: chrisyxlee/files-changed-action@v0.0.4
        with:
          include: |
            .github/workflows/go.yaml
            .*\.pb\.go
            go.mod
```

```text
 All files changed.
  go.mod
  go.sum
 Exclusion group.
  
 After filtering out excluded.
  go.mod
  go.sum
 Inclusion group.
  .github/workflows/go.yaml
  .*.pb.go
```

`go.mod` gets cut out.
